### PR TITLE
fix: parameter type for vim.fn.getline()

### PR DESCRIPTION
**Pull request by krapjost**

### CODE REVIEW

**Comment by folke** [comment]
Those files are auto generated. Please check some merged PRs on how to contribute

**Comment by krapjost** [comment]
> Those files are auto generated. Please check some merged PRs on how to contribute

I suppose i fixed..!

**Comment by krapjost** [comment]
And i want to ask you something.
If the return type is an array of strings or an empty array, is the type annotation something like "string[ ] | nil[ ]"?

**Comment by folke** [comment]
Thank you for the PR!

the type for an empty array or array of strings is still just `string[]`

**Pull request merged**
