### PR TITLE
chore: add uv error constants

### PR DESCRIPTION
**Pull request by mikesmithgh**
Hey @folke, I was looking at some of your lazy.nvim code and discovered `uv` 🙂. Learning a lot from your dev work.

I noticed `errno` is missing and added the values by running `errono -ls` on my Mac. I also added UNKOWN because I saw that when I inspected the uv.errno table. 

This has the same issue as constants in that the `errno` can change depending on the system, unix vs windows.

Reference: https://docs.libuv.org/en/v1.x/errors.html#error-constants

### CODE REVIEW

**Comment by folke** [comment]
Hi! That file is automatically fetched from the https://github.com/Bilal2453/luvit-meta repo, so would be better to open a PR there. Once it's merged it will be automatically picked up by neodev.

**Comment by mikesmithgh** [comment]
ahh Magic :joy: I'll open it there, thanks!

**Comment by mikesmithgh** [comment]
https://github.com/Bilal2453/luvit-meta/pull/2 merged and pulled into neodev 👍

**Comment by folke** [comment]
@mikesmithgh great! Thanks!

**Pull request closed without merging**
